pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Setup & Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
                sh 'npm start & echo $! > .pidfile'
                input message: '🔍 網頁啟動中，請打開 http://<Jenkins_IP>:3000 查看。看完後按 Proceed'
            }
        }
        stage('Shutdown') {
            steps {
                sh 'kill $(cat .pidfile)'
            }
        }
    }
}
