pipeline {
    agent any

    environment {
        CI = 'true'
    }
    
    tools {
    nodejs 'NodeJS 18'    // ← 這裡要跟 Global Tool Config 裡的 Name 一樣
    }
    
    stages {
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Serve App') {
            steps {
                sh '''
                    npm install -g serve
                    nohup serve -s build -l 3000 &
                    echo $! > serve.pid
                '''
                echo 'Web app is running at http://<jenkins-ip>:3000'
                input message: '查看完頁面後，請點繼續'
            }
        }

        stage('Cleanup') {
            steps {
                sh '''
                    if [ -f serve.pid ]; then
                      kill $(cat serve.pid) || true
                    fi
                '''
            }
        }
    }
}
